#!/usr/bin/env python
from pathlib import Path 
import os, sys

me = Path(__file__).resolve()
here = me.parent.resolve() 
bunBuild = here / 'build.js' 

cmds = ['build', 'serve']

assert len(sys.argv) == 3, "Usage: pres command target\n" + \
    f"Commands: {cmds}\n"

cmd = sys.argv[1]
assert cmd in cmds, f"Command {cmd} not in {cmds}"

target = Path(sys.argv[2])
assert target.exists(), f"Target {target} does not exist"

target = target.absolute()

cwd = os.getcwd()
os.chdir(here)

cmd = f"_PRES_VITE_ENTRY={target} bunx vite --config {bunBuild} {cmd}"
os.system(cmd)

os.chdir(cwd)
